### ISSUE TITLE
[Question] – Hints style

### ISSUE THREAD

**Issue by dotiful** [b0o/surfingkeys-conf#14]
Hello! Thanks for this awesome repo.
Exactly what I was looking for.
I have only one question, how can I add `Hints.style("css code")`?

**Comment by b0o** [comment]
You should be able add that directly inside `conf.js` and then re-compile with gulp. Let me know if you need more help!

**Comment by dotiful** [comment]
Already tried that, but got an error `ReferenceError: Hints is not defined`.
With `const Hints = require("./hints")` got another error `TypeError: Hints.style is not a function`.
seems i'm doing something wrong

**Comment by b0o** [comment]
Apologies for the delayed response - this should be fixed now, would you mind pulling the latest commit and trying again? Thank you!

**Comment by dotiful** [comment]
Thanks for your help, now it works as I expected 👍
