### ISSUE TITLE
Needs to overcome Omnibar restrictions

### ISSUE THREAD

**Issue by jaredbidlow** [b0o/surfingkeys-conf#2]
I post this here because it does not show results in the omnibar due to the latest restrictions placed on the extension

**Comment by b0o** [comment]
@jaredbidlow Right, this is unfortunate. I'm still using SurfingKeys 0.9.14 due to this. I will work on a solution in the near future.

**Comment by brookhong** [comment]
@b0o Looks like most of your settings could be fixed by returning an array of HTML string instead of calling `Omnibar.listResults` directly.

**Comment by b0o** [comment]
Fixed in 3dddf887454f4514b40c61f39ef5e47251592cd8, pending merge of https://github.com/brookhong/Surfingkeys/pull/815

**Comment by b0o** [comment]
The upstream fix has been merged but a release hasn't yet been cut, so this fix won't be supported by SurfingKeys until at least v0.9.38. You can manually install SurfingKeys HEAD until then.
