### ISSUE TITLE
Support for extended active window in full page screenshot keybinding.

### ISSUE THREAD

**Issue by ertwro** [b0o/surfingkeys-conf#28]
- Surfingkeys Version: 0.9.65
- Surfingkeys-conf Version (git hash): 7162fbca91c1e27fe1770948f7f6492ddc364a79
- Operating System: Windows 10 (version 2004)
- Browser Version: Brave Browser Version 1.10.93 Chromium: 83.0.4103.106 (Official Build) (64-bit)

## Details

When doing a full page screen-capture, either by <kbd>yG</kbd> or <kbd>yS</kbd> the normal behavior of surfingkeys-conf is to scroll and composite the screenshot. While this works most of the time, it varies depending on the level of zoom, changes one's current position on the page and it can be glitchy based on one's keyboard and mouse input during capture.

### [feature request]
While I get the current behavior is much more general and useful in other browsers, Chromium and Firefox expose a feature called _extended active window_. This feature takes the screenshot in the background making it zoom, input and animation independent.
Normally I get access to it in Chrome type browsers by doing:
1) Do ```inspect``` in developer tools by pressing <kbd>Ctrl</kbd><kbd>Shift</kbd><kbd>i</kbd>  or  <kbd>F12</kbd>
2) ```Run command``` by pressing <kbd>Ctrl</kbd><kbd>Shift</kbd><kbd>P</kbd>
3) writing >```capture full size screenshot```

If I knew enough javascript I would do a pullrequest instead of just mentioning a feature to dump work on you but I'm not a programmer. Maybe this is something you find worthy of including if is not too much work and useful.
Thanks for you awesome code.

**Comment by b0o** [comment]
`yG` and `yS`  are provided by SurfingKeys itself, not this project. This could possibly be implemented here, but do you think this request would fit better on the main SurfingKeys repo?

**Comment by ertwro** [comment]
I think the current behavior is much more portable and general. While _extended active window_ has been supported in several versions of Chrome and Firefox, at least since versions 35 and 30 respectively to my knowledge, I see how it could break at some point. Making it more suited for personal configuration. I'll ask in the Surfingkeys repo, keep this issue open while I wait for an opinion there. Feel free to close it. I would reopen it later if by any chance they see merit but think it would be more suited for personal configuration. If you don't mind.

[Issue 1263 on Surfingkeys](https://github.com/brookhong/Surfingkeys/issues/1263)
