### ISSUE TITLE
The following settings are invalid

### ISSUE THREAD

**Issue by sgrjyb** [b0o/surfingkeys-conf#3]
```js
// Search & completion
// Search leader
let sl = '';

// Search engines

var search = [
    { alias:  'yt' 
    , name:   'youtube'
    , search: 'https://www.youtube.com/search?q='
    , compl:  'https://www.googleapis.com/youtube/v3/search?maxResults=20&part=snippet&type=video,channel&key=__YOUR_API_KEY_HERE__&safeSearch=none&q='
    , callback: function(response) {
        var res = JSON.parse(response.text)["items"];
        Omnibar.listResults(res, function(s) {
          switch(s["id"]["kind"]) {
            case "youtube#channel":
              return Omnibar.createURLItem({
                title: s["snippet"]["channelTitle"] + ": " + s["snippet"]["description"],
                url:   "https://youtube.com/channel/" + s["id"]["channelId"]
              });
              break;
            case "youtube#video":
              return Omnibar.createURLItem({
                title: " ▶ " + s["snippet"]["title"],
                url:   "https://youtu.be/" + s["id"]["videoId"]
              });
              break;
          }
        });
      }
    }, 
 
];
for(var i = 0; i < search.length; i++) {
    var s  = search[i],    // Search object
        la = sl + s.alias; // Search leader + alias
    addSearchAliasX(s.alias, s.name, s.search, sl, s.compl, s.callback);
    mapkey(la, '#8Search ' + s.name, 'Front.openOmnibar({type: "SearchEngine", extra: "' + s.alias + '"})');
}


// Functions
function ytFullscreen() {
    $('.ytp-fullscreen-button.ytp-button').click();
}
function vimeoFullscreen() {
    $('.fullscreen-icon').click();
}
function j_display_pre() {
    $('div.media_bigpic_display_pre j_display_pre').click();
}
function j_display_next() {
    $('.media_bigpic_display_next j_display_next').click();
}

function fakeSpot() {
    var url = "http://fakespot.com/analyze?url=" + window.location.href;
    window.open(url, '_blank').focus();
}

function ghToggleStar() {
  var repo = window.location.pathname.slice(1).split("/").slice(0,2).join("/");
  var cur = $('div.starring-container > form').filter(function() {
    return $(this).css("display") === "block";
  });

  var action = "starred";
  var star = "★";
  if (cur.attr("class") === "starred") {
    action = "un" + action
    star = "☆"
  }

  cur.find("button").click();
  Front.showBanner(star + " Repository " + repo + " " + action);
}

function glToggleStar() {
  var repo = window.location.pathname.slice(1).split("/").slice(0,2).join("/");
  var action = $('.btn.star-btn > span').click().text().toLowerCase() + "red";
  var star = "☆";
  if (action === "starred") {
    star = "★";
  }
  Front.showBanner(star + " Repository " + repo + " " + action);
}

function redditCollapseComment() {
    $('body > .content .commentarea > .sitetable > .noncollapsed:first > .entry > .tagline > .expand:first').click();
}
```

**Comment by b0o** [comment]
Hey @sgrjyb, what version of SurfingKeys are you using?

My configuration only officially supports SurfingKeys v0.9.14 and below. More recent versions changed the Omnibar API which breaks most of the custom search engine completions.

I tested your code on v0.9.14 and it seems to work for me.

**Comment by sgrjyb** [comment]
@b0o  0.9.31 

1.Can you fix this?
function ghToggleStar() {
  var repo = window.location.pathname.slice(1).split("/").slice(0,2).join("/");
  var cur = $('div.starring-container > form').filter(function() {
    return $(this).css("display") === "block";
  });

  var action = "starred";
  var star = "★";
  if (cur.attr("class") === "starred") {
    action = "un" + action
    star = "☆"
  }

  cur.find("button").click();
  Front.showBanner(star + " Repository " + repo + " " + action);
}


// Search leader
let sl = 'o';

// Search engines
var search = [
    { alias:  'yt' 
    , name:   'youtube'
    , search: 'https://www.youtube.com/results?search_query='
    }, 
var search = [
    { alias:  'yk' 
    , name:   'youku'
    , search: 'https://www.youku.com/search?q='
];

2. yt Open to search
for(var i = 0; i < search.length; i++) {
    var s  = search[i],    // Search object
        la = sl + s.alias; // Search leader + alias

    addSearchAliasX(s.alias, s.name, s.search, sl, s.compl, s.callback);
}

mapkey(la, '#8Search with ' + s.name, function() {
    Front.openOmnibar({type: "SearchEngine", extra: s.alias, tabbed: false});
});

**Comment by b0o** [comment]
@sgrjyb Can you please fix your code formatting? 

https://help.github.com/articles/basic-writing-and-formatting-syntax/#quoting-code

Also, I unfortunately won't be able to fix anything which deals with the Omnibar at this time.

**Comment by b0o** [comment]
Closing this as a duplicate

**Comment by sgrjyb** [comment]
The new version needs to change mapkey(la, '#8Search ' + s.name, 'Front.openOmnibar({type: "SearchEngine", extra: "' + s.alias + '"})'); 
to 
mapkey (la , '#8Search' + s.name, function() { Front.openOmnibar({type: "SearchEngine", extra: s.alias}); });
