### ISSUE TITLE
Default search engine?

### ISSUE THREAD

**Issue by StoicIndividual** [b0o/surfingkeys-conf#35]
- Surfingkeys Version: 0.9.69
- Surfingkeys-conf Version (git hash): b6b0f99
- Operating System: Linux Mint 20.1 Cinnamon
- Browser Version: Brave browser Version 1.21.51

## Details
when pressing "t" and typing my search query no default search engine is selected, since I prefer using duckduckgo I have to type "dd" before every search query or use "add", is that the correct way of using this config or is there a setting that I'm missing?

**Comment by b0o** [comment]
Thanks for reporting! Fixed in 9623762b5f553e407f29c4f8b6b92da8778ad2bb.
