### ISSUE TITLE
When let sl = '' is equal to the blank, the 's' + alias key is added to search for the selected text. How to change this to addSearchAliasX('h', 'github', 'https://github.com/search?o=desc&s= Updated&type=Repositories&utf8=%E2%9C%93&q=', 'g');

### ISSUE THREAD

**Issue by iwanfu** [b0o/surfingkeys-conf#4]
let sl = '';

// Search engines

var search = [
    { alias:  'yt' 
    , name:   'youtube'
    , search: 'https://www.youtube.com/results?search_query='
    , compl:  'https://suggestqueries.google.com/complete/search?client=youtube&ds=yt&client=chrome-ext&q='
    , callback: function(response) {
         var res = JSON.parse(response.text);
         return res[1];
      }
    }, 
    { alias:  'am'
    , name:   'amazon'
    , search: 'https://amazon.com/s/?field-keywords='
    , compl:  'https://completion.amazon.com/search/complete?method=completion&mkt=44551&p=Search&l=es_ES&b2b=0&fresh=0&client=amazon-search-ui&x=String&search-alias=aps&ks=69&q='
    , callback: function(response) {
        var regex = /[^[\]]+(?=])/;
        var matched = regex.exec(response.text);
        return matched[0]
            .split(',')
            .map(item => item.substring(1, item.length-1));
      }
    }
    ]

for(var i = 0; i < search.length; i++) {
    var s  = search[i],    // Search object
        la = sl + s.alias; // Search leader + alias

    addSearchAliasX(s.alias, s.name, s.search, sl, s.compl, s.callback);

}

mapkey('yt', '#8Open omnibar for ' + s.name, function() {
    Front.openOmnibar({type: "SearchEngine", extra: 'yt' });
});
mapkey('am', '#8Open omnibar for ' + s.name, function() {
    Front.openOmnibar({type: "SearchEngine", extra: 'am' });
});

2.Please help me change

addSearchAliasX('t', 'taobao', 'https://s.taobao.com/search?q=', 's', 'https://suggest.taobao.com/sug?code=utf-8&q=', function(response) {
    var res = eval("a=" + response.text);
    res = res.result.map(function(r) {
        return r[0];
    });
    Omnibar.listWords(res);
});

**Comment by b0o** [comment]
I'm going to close this because I can't quite understand the question. If you're still having trouble, please open a new issue. Thanks 😃

**Comment by iwanfu** [comment]
@b0o `Increase open search key${s.alias}` 

`const searchleader = ""`
`  
alias:  "oy",
openOmnibar:  "oy",
searchkey: "yt"
`
![a](https://user-images.githubusercontent.com/28247198/48674676-bc7aa000-eb89-11e8-95fd-0381fc6a02d5.PNG)
![s](https://user-images.githubusercontent.com/28247198/48674677-bd133680-eb89-11e8-9d61-9353e53a335f.PNG)

**Comment by iwanfu** [comment]
@b0o 

`search_leader_key`

![s](https://user-images.githubusercontent.com/28247198/48674677-bd133680-eb89-11e8-9d61-9353e53a335f.PNG)

``` js
addSearchAliasX('d', 'duckduckgo', 'https://duckduckgo.com/?q=', 'c', 'https://duckduckgo.com/ac/?q=', function(response) {
    var res = JSON.parse(response.text);
    return res.map(function(r){
        return r.phrase;
    });
});
```
